let dados = [
    {
        titulo: "Porquê me interessei por você",
        descricao: "Não há muita explicação para isso, eu simplesmente cheguei na sala, começei a olhar quem estava na sala, e mesmo antes de estar lá dentro eu te vi e me chamou muita atenção a sua beleza, te achei linda com esses cabelos longos, lisos. Eu achei que só seria mais uma menina linda que não iria se interessar por mim, e ficava em choque quando você, obviamente, mostrava interesse por mim, ficava pensando ou falando com Gabriel para ter certeza que não era coisa da minha cabeça. E caso queira saber quanto tempo passou desde que a gente se viu pela primeira vez é só clicar aqui.",
        link: "https://www.mobills.com.br/calculadoras/contador-de-dias/resultado/?data-inicio=2023-02-06&data-final=2024-10-06"
    },
    {
        titulo: "Ao te conhecer...",
        descricao: "Após o primeiro dia, (que nos encontramos quando apenas fui ver o horário kkkk) e falei pela primeira vez com você, e assim se deu o inicío de tudo. A cada dia que eu ia para o colégio, quase sempre acontecia algo que nos aproximava, e eu diria que vc fez bem mais no inicio para a gente se aproximar, você que deu as iniciativas. Lembro que teve uma brincadeira em dupla que algum prof passou, nela tava eu e Gabrel brincando, você e sua dupla acabaram cedo, ai você chegou e sentou perto de mim, perguntando se podia ficar lá, como eu ia recusar véi KKKKKKKKKKK, nessa hora eu gelei, olhei pra Gabriel e ele entendeu, e na saída desse msm dia, eu sai muito nervoso, e nesse dia Gabriel também teve 100% de certeza que você gostava de eu. Após isso fomos nos aproximando, conversando pelo insta e tals, você era bem calminha porque não demonstrava oque sentia pra eu. Ai veio nosso primeiro beijo..."
    },
    {
        titulo: "O primeiro de muitos",
        descricao: "Começamos a conversar muito frequentemente, quase todo dia, nos conhecemos melhor, começei a te acompanhar até em casa, e ai veio... Em um dia como qualquer outro para nós dois, em um clima de chuva, ruas cheias de lama, na despedida você me deu um beijo, tão inesperado, tão bom, de arrepiar, numa situação tão aleatória em que sua vó estava vindo. Voltei para casa voando, não de velocidade, e sim nos pensamentos. Fui no automático pensando naquele beijo, não acreditava no que aconteceu KKKKKKKKKKK, muita vergonha, não sabia oque dizer ou falar quando chegar, apenas um branco. E ainda me lembro do dia, caso não se lembre só clicar aqui.",
        link: "https://www.mobills.com.br/calculadoras/contador-de-dias/resultado/?data-inicio=2023-03-21&data-final=2024-10-06"
    },
    {
        titulo: "Amigo ou inimigo?",
        descricao: "No meio disso tudo, do processo da gente se conhecer e tals, tinha Salatiel, diria que foi uma pessoa \"importante no processo\". Juro que não sei se ele me ajudava ou se ele era o famoso talarico. Muitas vezes ele vinha me falar de você, que você tava afim de eu e tals, mas as vezes você vinha dizer que ele tava dando em cima de você, juro que ficava confuso. Ele me insentivava a ir falar com você, puxar assunto, mas sla, cara estranho véi."
    },
    {
        titulo: "Amor louco",
        descricao: "Véi, tava aqui pensando, a gente é louco viu KKKKKKKKKKKK, primeiro aquele beijo perigosíssimo com sua vó vindo, teve aquela vez que fui na casa da sua tia, o que eu fiquei peocupado com as vizinhas dela n tava escrito, você indo para casa fazer coisas com eu pela primeira vez saindo escondida da sua tia,ou melhor, você quase sempre sai escondida né? jesus amado, me assume ai. No inicío eu tinha mt medo de alguém descobrir, ainda tenho, mas não tanto quanto antes. Mas véi, você faz muita loucura comigo, sério mesmo, assim você me mata do coração. Sem falar das vezes que a gente já se pegou na sua casa escondidos da sua mãe, ou aquela vez que não tinha ngm na sua casa. Tanta loucura que jesuis."
    },
    {
        titulo: "Primeira vez",
        descricao: "Mais um dia normal, ou melhor, achava que era, não acreditei, fiquei mt nervoso, limpei a casa toda pra te receber, deu nem para eu tomar um banho mds, não acreditei que isso iria realmente acontecer, você é maluca véi, só pode. Tava lá, a criança na casa da Tia Judith dela, e saindo falando que ia para a casa da mãe, a maior mentira, não pensa na consequência que seria se ela descobrisse é doida? KKKKKKKKKKK. E você realmente chegou, conversamos um pouco, bem pouco mesmo, porque estava estampado na sua testa o que realmente queira, aquele dia foi quente ein. Foi maravilhoso, eu amei sério (e continuo amando, rsrsrs), a unica coisa que não gostei foi o sangue, mas de certa forma dava um alívio, pois ali tive certeza que era sua primeira vez também... acho que era o que eu queria, ter minha primeira vez com alguém que me ame e que também tenha sua primeira vez, ai bb sério, te amuuuuuu mtttttttttt."
    },
    {
        titulo: "Altos e baixos...",
        descricao: "É né, nem tudo é perfeito e sai como queremos né? já errei muitas vezes com você... peço mil desculpas para você, ja fiz coisas erradas, ja me arrependi bastante, dói muito errar com você, dói ouvir você falar de forma grossa comigo, ou brigando comigo, tendo motivo ou não, dói, é estressante ser culpado muitas vezes por nada, por um errinho besta, é horrivel ver você daquele jeito... Mas independente do que está acontecendo, independente das nossas brigas, independente de tudo, eu te amo, com toda certeza, te dou as chances que precisar para melhorar, não vou desistir de você tão fácil, é cansativo para mim ver tantas falhas, é obvio que é, mas não irei desistir de te amar tão fácil, pode tentar quantas vezes quiser tá? vou fazer meu máximo para te suportar quando está chata e irritada, brigando comigo por nada, me ignorando ou sla. Mas nunca esqueça, que cada vez que você fica daquele jeito, eu fico bem mal, não sabe o quanto quero chorar ou machucar... e você nunca faz eu soltar, admito que seguro tudo, as vezes você faz eu soltar, mas nem sempre é assim, lembra do roxo que deixei no braço? você não imagina o que está por trás para isso acontecer? pse... Mas saiba, eu te amo, e vou continuar amando, espero o dia que poderei ser assumido, o dia que iremos morar juntos e ir adiante juntos, vai que no dia que eu te entregue isso você já tenha me assumido né? FKLJSDFKLJSHDFKLJKSLDJ, mas é triste pensar que espero isso a muito tempo e que ja disse isso várias vezes... Desculpa por esse texto triste, eu te amo muito ta bb?"
    },
    {
        titulo: "Você presente vs Você longe",
        descricao: "Eu amoo muitoo quando eu te vejo bb, de preferência fora da escola né, ninguém merece. Pessoalmente, fora da escola é muito bom te ver, sair para comer açaí, sorvete, salgado e tals. A gente fazer coisas na minha casa, comer, jogar e tals, brincamos muito, rimos muito. E quando estamos por mensagem ou call que a coisa fica ruim, obviamente não é sempre, mas muitas vezes acontece da gente brigar, desentender, as vezes muito feio. Tento manter a paciência mas não dá certo, também acontece esse tipo de coisa quando estamos juntos mas bem raramente, e é mais fácil de resolver por eu estar presente e conseguir fazezr você me ouvir sabe? o problema é quando acontece na escola, que também é muito frequênte, na escola não posso te segurar ou falar alto, se não você grita e quem se lasca é sempre eu bb, e você ameaça ir no banheiro fazer sei lá o que me deixa muito triste e com raiva. Mas faço o que posso por você. Resumindo, prefiro ficar pessoalmente com você, muito melhor, sério mesmo."
    },
    {
        titulo: "Nossas Brigas...",
        descricao: "Aqui irei desabafar muito, falarei tudo, e você lê quando estiver pronta, coisas que eu não falaria para você porquê não quero brigas, já temos de mais né? são coisas que seguro para não aumentar a briga e durar mais tempo, e talvez esclareça algo para você também, talvez te ajude a entender o quer sinto ou como deve me ajudar num sei (e antes de tudo, eu te amoo muiiittooo bb, independente do que eu falar, não se esqueça. E não, não quero terminar). Sobre nossas brigas bb, principalemte por calls ou mensagens que é onde mais acontece, eu não gosto nenhum pouco de como você age nessas horas, e as vezes é por motivos muito bestas, talvez porque falei algo que você não gostou, porquê brinquei de forma que você não gostou, resumindo você fica brava por qualquer coisa que você não quer ou não gosta. Na verdade eu tento manter a paciência mas eu também tenho meus limites de paciência, uma hora vou ficar com raiva ou estourar. Mas véi eu tento muito ser legalzinho com você nessas horas mesmo com raiva, me da mais raiva ainda quando você fala fala direito cmg e se eu não falar desliga. Essa frase é uma tortura véi, se nem vc faz pq eu tenho? no início eu tento falar direito com você para resolver antes que algo maior aconteça sabe? Mas tem vezes que eu solto um pouco do que sinto ou o que penso, ai por ser algo que você não gosta, você fica mais brava ainda, me fazendo ter que engolir tudo calado sem falar o que penso, pois se eu falar só piora, tenho que aceitar o que você fala querendo ou não. Obviamente, tem vezes que vou estar tão feliz que não vou me inportar e vou só aceitar e ignorar sua raiva, tem vezes que vou estar feliz e ficar com raiva de você porquê você reclama até se eu rir ou ficar sorrindo, tem vezes que vou ficar com raiva de vez, vezes que estarei calmo, e talvez perder a calma depois, ou vezes que ficarei rindo com vontade de chorar, tipo ontem (24/09/24) na aula de redação... Quando você está com raiva parece que não se importa nenhum pouco comigo, com o que diz, só quer saber de você mesma, que eu faça apenas o que você quer, você tem que aprender que nem tudo é do jeito que você quer, que não poderei fazer tudo que quer."
    },
    {
        titulo: "Nossas calls",
        descricao: "Eu gosto tanto quando da tudo certo em nossas calls, queria ter mais tempo as vezes para jogar coisas diferentes com você, não só brawl stars. Na verdade gostaria que seu celular aguentasse outros jogos mais pesados, principalmente no roblox, os jogos que gosto você ficatravando tadinha. Gosto tanto quando brincamos, rimos, zoamos nos jogos. As vezes estou mortojogando com você, estou mass releva KKKKKKKKKK, eu gosto independente. Queria tanto que vocêestivesse do meu lado jogando comigo, não só em call. Imagina a gente jogando minecraft no pc juntos, ou roblox, você no meu celular para não travar, ou você usar seu notebook para jogar comigo, só levar lá para casa, posso comprar um mouse para você caso você goste, as vezes sinto que você não gosta tanto de jogar. Você tem uma mente muito fechada para receber coisas novas, tipo jogos de vários tipos diferentes. Por favor, não ache que não gosto das calls, como já disse, só gostaria de dar uma variada no tempo que jogo, no tempo que fico em call com você, nos jogos que a gente joga, e tals tendeu?"
    },
    {
        titulo: "Consolos da princesa",
        descricao: "Se você está lendo isso minha princesa, deve ser porquê está triste né? ou talvez com autoestima baixa, ou até mesmo lendo por ler. Antes de mais nada bb, saiba que eu te amo muito mesmo tá? e para sempre, não pense que irá acabar. Se você errou comigo e está aqui, vai em mim, pede desculpas e tenta se explicar, com calma e de vagar, tentando responder todas minhas perguntas. Se você está triste ou com autoestima baixa, vai em mim bb, me conta o que está sentindo, avisa que quer desabafar bb. Mas não precisa se diminuir a outras tá? Você é a mulher mais linda que já vi, eu te amo para sempre, eu te amo mais que todo o universo, mesmo que ele continue crescendo eu estarei te amando mais que tudo neste mundo. Você é minha bbzinha fofinha, linda, maravilhosa, não me canso de falar tudo que vejo em você mesmo que eu repita as mesmas coisas, saiba que é porque não sei palavras para te descrever do jeito que eu te vejo. Se for seu corpo então, aiai, eu adoro, é lindo por si só, é maravilhoso de ver, de tocar. Se está se achando magra de mais, não me importo nenhum pouco, se seu corpo já é tudo isso, imagina o jeito que você quer ser, ser mais gostosa ainda? KKKKKKKK aiai, agradeço, mas por mim você é mais gostosa que qualquer outra. Cada milímetro do seu corpo é perfeito, é lindo, é muito gostoso. Fico até com vontade só de imaginar você nua, é tão linda que você não tem noção. Se não for isso, saiba que sempre vou te perdoar, sempre vou esperar que você melhore, sempre estárei te esperando se me prometer mostrar resultados, eu sei que você consegue bb, continue olhando para frente, não importa o que aconteça tá? não sei se você lembra mas sempre continue tentando enquanto tiver chance, mesmo se a chance de vencer seja de 1 em 1000000, tente mais que nunca e faça ser nessa vez."
    },
    {
        titulo: "Todo o tempo do mundo",
        descricao: 'É o que eu queria ter, gosto de fazer minhas coisas sabe? eu durmo a hora exata que um humando precisa, me sinto preso a uma rotina fixa, as gostaria de variar as vezes sabe? um dia fazer mais de tal coisa do que outra. Mas sinto que você fica triste se eu fizer o que me deixa feliz, sinto que sou obrigado a aproveitar o tempo que você me deu e apenas ele sabe? quando fico a mais, você fica brava, triste, chateada ou sei lá, se eu fico menos, eu saio prejudicado. Você deveria saber o porquê eu ultimamente quero tanto jogar bb, eu sempre fiz muito por você, sempre dou todo meu tempo para você, querendo ou não você passa a tarde toda comigo, (e na escola você também fica brava se eu ficar "de mais" conversando com meus amigos) mesmo que você ofereça pra eu ficar mais, pra eu ir conversar com meus amigos, eu nunca aceito, sabe pq? porquê tenho medo de você ficar mal de alguma forma, se você quiser saber se to bem, pede uma foto das minhas partidas de valorant que você vai saber em quais eu estava incomodado se você ia ficar brava ou não, obviamente não vai ser sempre este o motivo, mas é bom perguntar sabe? as vezes mato menos por não estar focando direito no jogo por estar pensando nisso ou em algo, as vezes poquer não estou conseguindo mesmo pelos caras serem bons. Queria que você morasse com eu, mas também tenho medo de você pegar mais tempo ainda de mim, me deixar com quase nada. Tenho fé que a gente se ver mais, vai abrir mais tempo para mim, pelo menos espero, porque ja te dou tanto tempo e atenção, alguns são desperdiçados por você ficar brava por nada ou por algo que não precisava de tanta raiva sabe? é só tempo jogado no lixo para mim, eu poderia estar jogando, dormindo, ou brincando com você nesse tempo perdido sabe? hoje cada minuto importa bb. Torço para a escola acabar para eu ter mais tempo para mim, porque todo meu tempo livre te dou, no meio da semana tenho 1 hora para jogar, se eu for rápido até 1:30, mesmo você oferencendo já falei bb, não me sinto confortável em aceitar, não me convence que você vai estar 100% bem. Não entendo, você fica tão mal por me deixar fazer algo que você sabe que me deixaria melhor, mais aliviado. Eu querer jogar mais não é porque te amo menos, que não quero ficar com você bb, espero que um dia você entenda. Tem vezes que dá vontadede te evitar por você estar brava daquele jeito, não gosto nenhum pouco sério mesmo.'
    },
    {
        titulo: "Amor",
        descricao: "Eu te amo, simplesmente te amo. Eu tenho fé e esperança em você, desculpa por já ter pensado em romper nossas correntes, mas é que é difícil viver as escondidas, desculpa mesmo minha princesa. Você conseguiu quebrar as muralhas e minha armadura, conseguiu me transformar, conseguiu mudar meu coração, transformou meu coração de pedra em um capaz de amar novamente, e como nunca antes. Você me acalma quando está calma, você é o abraço que gostaria de correr atrás, é o abraço que acalma minha alma. Amo você, quando está calma, cuida de mim, me abraça, tem paciência, me ouve, me entende e me ajuda. Irei viver com seu amor, até que um dia ele morra novamente, mas espero que façamos deste um amor eterno, um amor sem fim e vasto. Obrigado por me libertar de meus vicíos, de meus pensamentos, por cuidar de mim, por me fazer evoluir, por me mostrar coisas novas, por me libertar de todas as correntes que me atrasavam, espero que continue acolhendo meus choros e sentimentos, espero que tenha paciência quando eu estiver mal de qualquer forma, eu te amo. Façamos deste um amor que transborde sem parar, um amor onde nos sentimos seguros, eu sempre farei você se sentir amada, e te darei tudo que tenho pelo nosso amor e pelo seu bem. Deixa eu me jogar no seus abraços, tenha paciência e cuide de mim, faça tudo que puder por mim, n me faça temer sorrir, nunca fale que quer me ver triste ou infeliz, não alimente meu medo, se não só criará mais peso para mim, espero poder correr e confiar em você de olhos fechados, me faça confiar que você não ficará brava por coisas fúteis, não quero viver sem você até cair no sono. Quero que você seja o amor da minha vida, o meu sopro de vida que flui em minha alma. Obrigado por tudo princesa, eu te amo e te entregarei tudo que tenho pelo nosso amor."
    },
    {
        titulo: "O futuro que nos aguarda",
        descricao: "Espero que nosso futuro seja nós dois juntos, eu realmente não sei como será daqui para frente, será uma vida nova tanto para mim quanto para você. Mas vamos de um passo de cada vez né? vai saber se a gente mora junto já ano que vem, ou daqui 2, 3 anos. Realmente não sei o que pode acontecer daqui para frente, mas quero estar junto á você sempre, viver juntos, sair juntos, contruir uma familia juntos. E quero morar junto com você logo, aguento viver com as pestes lá de casa não. Espero que temos uma estabilidade financeira muito boa, é a coisa que mais tenho preocupação, mas creio eu que vai dar tudo certo nesse quisito. Também tenho medo de um filho vir muito cedo e acabar quebrando a nossa estabilidade que ainda está sendo formada sabe? o meu principal medo de ter filho é porquê não temos dinheiro pra sustentar não, sua familia muito menos. Faremos de tudo para ter um apenas quando tivermos onde morar, tivermos dinheiro de sobra, e uma vida boa e calma tá? Espero poder te encontrar na minha casa e acordar todos os dias ao seu lado em breve bb. Estou Orando para que tudo dê certo, que você me assuma logo para a gente já ir pensando nisso, quanto mais demorar para me assumir, mais nosso futuro será adiado, é no que penso desde quando soube que não seria assumido tão cedo, sempre adiando, sempre me enrolando, me deixando criar esperança por mais de 1 ano, falando sempre que seria esse mês ou no que vem, ao invés de falar que seria depois dos 18 anos, eu perguntava mas você falava que antes dos 18 você já teria me assumido, acreditei em você por 1 ano sempre adiando, tem prova de amor e confiança melhor? e ainda vai ter a coragem de dizer que não te amo ou que não confio em você? aiai viu, olhe para trás e veja tudo que fiz, e o tanto que esperei pela gente antes de dizer tais coisas tá? Te espero no meu futuro minha princesa."
    },
    {
        titulo: "eu te amo mil milhões",
        descricao: "bb eu te amo tanntooo, que acho que nem eu sei o quanto, muito menos você, não gosto quando você fala que não te amo ou que não cuido de você, pois parece que não faço o suficiente para você. Eu te amo a um nivel bb, eu te adoro, eu quero que minha vida evolua com você, pode ser? não pretendo te abandonar, nem brigar, muito menos te agredir KKKKKKK. Eu irei cuidar de você, se por algum acaso eu começar algo que não goste me fale, se eu te agredir, termina comigo tá? sem dó, por favor. Pois prefiro você bem, sem se machucar comigo, do que se machucando comigo, sua prioridade é o seu cuidado tá bb? Mas farei de tudo para te manter bem princesa, darei tudo que puder para te fazer feliz e bem. Eu te amo minha princesa, muiiittooo mesmooooo, desculpa se não é o suficiente para demonstrar o quanto amo, é difícil descrever o tanto, juro, apenas te amo porque sim minha linda. Isso é tudo que posso te entregar bb."
    },
    {
        titulo: "Confiança a baixo de zero ou a cima de mil",
        descricao: "Eu confio em você, muito mesmo, cegamente. Mas sei lá, quando eu estou triste e você fica pior que eu por conta de mim mesmo, eu não me sinto confortávelem falar oque sinto bb, nessas horas a confiança não cobre tá? mas quando eu sei que você está pensando direito, tá com paciência e tals, eu confio em você para falar tudo tá? espero que você confie em mim igual a mim com você, desculpe pelos meu erros que fizeram sua confiança ser questionada, mas saiba que farei tudo para te mostrar que você pode confiar em mim, farei de tudo para te fazer bem, mas fique atenta que esse fazer tudo pode me deixar mal ta? KKKKKKKK posso acabar passando do limite as vezes, peço para que cuide de mim e não perca a cabeça e só brigue comigo, isso pode me afetar bb, nosso ralacionamento não é só sobre você estar bem ou não, somos eu e você, somos nós, um cuidando do outro certo? peço para que confie em mim, quando tiver dúvidas, vou fazer de tudo para levar a gente para o melhor caminho. Te amo minha princesa, confio em você tá? espero que entenda as vezes que eu não confio."
    }
];
